//Script to check that the results of a search with "inurl:" in the query have a url that contains the query

//Creation of a Chrome instance:
my_bro = Browser("Chrome")

//Navigation to google
my_bro.Goto("www.google.com")

//Find the query field
my_query = my_bro.SearchItem("lst-ib")

//Get the text to submit
query = "inurl: gouv.fr"

//Extract the argument in the query
content = extract_after(query, "inurl: ")

//Submit a query
my_query.Submit(query)

//Get the list of url results
results = my_bro.SearchTheItems("iUh30")

//Check that all the results have the argument "content" in their url
check = find_in_list(content, results)

//Display of the result
If check then 
  display("All results have " + content + " in their url") 
else 
  display("Some results don't have " + content + " in their url")
end if
