//Script to check that the results of a search with "site:" in the query are on the right host

//Creation of a Chrome instance:
my_bro = Browser("Chrome")

//Navigation to google
my_bro.Goto("www.google.com")

//Find the query field
my_query = my_bro.SearchItem("lst-ib")

//Get the text to submit
query = "javascript site: openclassrooms.com"

//Extract the argument in the query
site = extract_after(query, "site: ")

//Submit a query
my_query.Submit(query)

//Get the list of results
results = my_bro.SearchTheItems("LC201b")

//Checking if all the items in the list contain the "site"
check = find_in_list(site, results)

//Display of the result
If check then 
  display("All results are in " + site) 
else 
  display("There are some results that are not in " + site + "!")
